# Generated by Django 5.0.6 on 2024-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0005_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
